theme:
    icon:
        logo: material/home
    name: material
    palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-5
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-auto
        name: "Switch to system preference"
    features:
        - navigation.instant # 现在页面不会跳转,而是类似单页应用,搜索和各种跳转都是在当前页面完成,对美观有很大帮助
        - navigation.tabs # 页面上方的标签页
        - navigation.tracking # 页面滚动时，导航栏高亮当前页面
        - navigation.sections # 使导航栏分块
        - navigation.expand # 默认展开导航
        - navigation.prune # 只渲染当前页面的导航
        - toc.follow # 滚动的时候侧边栏自动跟随
        - navigation.top # 返回顶部按钮
        - search.suggest # 补全建议
        - search.highlight # 搜索结果高亮
        - search.share # 搜索结果分享
        - navigation.footer # 页脚提示下一章
        - content.code.copy # 代码段上的赋值按钮

markdown_extensions:
    - admonition # 警告语法
    - def_list
    - footnotes
    - abbr
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - md_in_html
    - pymdownx.arithmatex: # latex支持
          generic: true
    - toc:
          permalink: true # 固定标题位置为当前位置
          toc_depth: 3 # 目录深度
    - pymdownx.highlight: # 代码块高亮
          anchor_linenums: true
          linenums: true # 显示行号
          use_pygments: true # 代码高亮
          pygments_lang_class: true
          auto_title: true # 显示编程语言名称
          linenums_style: pymdownx-inline # 行号样式,防止复制的时候复制行号
    - pymdownx.betterem # 强调美化,比如**text**会被美化
    - pymdownx.caret # 上标和下标
    - pymdownx.mark # 上标和下标
    - pymdownx.tilde # 上标和下标
    - pymdownx.keys # 显示按键组合
    - pymdownx.critic
    - pymdownx.details # 可以折叠的代码块 ??? note 可以让警告变成折叠的
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.magiclink # 自动识别链接
    - pymdownx.smartsymbols # 智能符号
    - pymdownx.snippets # 代码段
    - pymdownx.tasklist:
        custom_checkbox: true # 自定义复选框
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.superfences: # 代码块中支持Mermaid
        custom_fences: # 支持 Mermaid
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
        combine_header_slug: true
    - pymdownx.tasklist:
        custom_checkbox: true
        clickable_checkbox: true
    - meta # 支持Markdown文件上方自定义标题标签等
    - tables

# 下面的是需要自定义的内容，请不要修改上方的内容，上面都是在开启各种插件和功能

site_name: GFM-RAG
docs_dir: .
nav:
  - Home: README.md
  - Installation: docs/install.md
  - Getting Started:
    - Data Preparation: docs/workflow/data_preparation.md
    - KG-index Construction: docs/workflow/kg_index.md
    - Retrieve with GFM-RAG: docs/workflow/inference.md
    - GFM-RAG Pretraining: docs/workflow/pretrain.md
    - GFM-RAG Fine-tuning: docs/workflow/finetune.md
  - Config:
    - KG-index Config: docs/config/kg_index_config.md
    - NER Model Config: docs/config/ner_model_config.md
    - Entity Linking Model Config: docs/config/el_model_config.md
    - OpenIE Model Config: docs/config/openie_model_config.md
  - API Reference:
    - KG-index Constructor: docs/api/kg_indexer.md
    - GFM Retriever: docs/api/gfmrag_retriever.md
    - Document Ranker: docs/api/doc_ranker.md
    - KG Construnction:
      - KG Constructor: docs/api/kg_construnction/kg_constructor.md
      - QA Constructor: docs/api/kg_construnction/qa_constructor.md
      - NER Model: docs/api/kg_construnction/ner_model.md
      - Entity Linking Model: docs/api/kg_construnction/el_model.md
      - OpenIE Model: docs/api/kg_construnction/openie_model.md
repo_url: https://github.com/RManLuo/gfm-rag.git
repo_name: gfm-rag

plugins:
    - search  # 内置插件，在标题中添加了一个搜索栏，允许用户搜索您的文档
    - autorefs
    - same-dir
    - mkdocstrings:
        handlers:
          python:
            paths: [gfmrag]
            options:
              show_root_heading: true
              show_symbol_type_heading: true
              show_source: true
              show_root_toc_entry: false
            import:
              - url: https://docs.python.org/3/objects.inv
                domains: [std, py]

# extra:
#     # generator: false  #删除页脚显示“使用 MkDocs 材料制造”
#     social:
#         - icon: fontawesome/brands/github
#           link: https://github.com/271374667
#           name: GitHub
#         - icon: fontawesome/brands/bilibili
#           link: https://space.bilibili.com/282527875
#           name: Bilibili
#         - icon: material/email
#           link: Python调包侠:<271374667@qq.com>
#           name: Email
