hydra:
  run:
    dir: outputs/qa_finetune/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - doc_ranker: idf_topk_ranker

seed: 1024

datasets:
  _target_: deep_graphrag.datasets.QADataset
  cfgs:
    root: ./data
    text_emb_model_name: sentence-transformers/all-mpnet-base-v2
  data_names:
    - hotpotqa

model:
  _target_: deep_graphrag.models.UltraQA
  init_entities_weight: True
  entity_model_cfg:
    _target_: deep_graphrag.ultra.models.QueryNBFNet
    input_dim: 64
    hidden_dims: [64, 64, 64, 64, 64, 64]
    message_func: distmult
    aggregate_func: sum
    short_cut: yes
    layer_norm: yes

task:
  strict_negative: yes
  adversarial_temperature: 0.2
  sample_weight: no
  metric: [mrr, hits@1, hits@2, hits@3, hits@5, hits@10, hits@20, hits@50, hits@100]

optimizer:
  _target_: torch.optim.AdamW
  lr: 5.0e-4

train:
  batch_size: 8
  num_epoch: 20
  log_interval: 100
  batch_per_epoch: null
  save_best_only: yes
  save_pretrained: yes # Save the model for QA inference
  train_test_split: [0.8, 0.2]

checkpoint: null
