hydra:
  run:
    dir: outputs/qa_finetune/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - doc_ranker: topk_ranker

seed: 1024

dataset:
  root: ./data
  data_name: hotpotqa_example
  text_emb_model_name: sentence-transformers/all-mpnet-base-v2

model:
  _target_: deep_graphrag.ultra.models.UltraQA
  entity_model_cfg:
    _target_: deep_graphrag.ultra.models.QueryNBFNet
    input_dim: 64
    hidden_dims: [64, 64, 64, 64, 64, 64]
    message_func: distmult
    aggregate_func: sum
    short_cut: yes
    layer_norm: yes

task:
  name: TransductiveInference
  strict_negative: yes
  adversarial_temperature: 0.2
  sample_weight: no
  metric: [mrr, hits@1, hits@3, hits@5, hits@10, hits@20, hits@50, hits@100]

optimizer:
  _target_: torch.optim.AdamW
  lr: 5.0e-4

train:
  batch_size: 8
  num_epoch: 20
  log_interval: 100
  batch_per_epoch: null
  train_test_split: [0.8, 0.2]

checkpoint: null
